In [1]:
import numpy as np

# Define fuzzy sets
A = [0.2, 0.5, 0.7, 0.9]
B = [0.3, 0.6, 0.4, 0.8]

print("Fuzzy Set A =", A)
print("Fuzzy Set B =", B)

# Union
union = [max(a, b) for a, b in zip(A, B)]
print("\nUnion of A and B =", union)

# Intersection
intersection = [min(a, b) for a, b in zip(A, B)]
print("Intersection of A and B =", intersection)

# Complement
complement_A = [1 - a for a in A]
print("Complement of A =", complement_A)

# Difference A-B
difference = [min(a, 1 - b) for a, b in zip(A, B)]
print("Difference A-B =", difference)

# Cartesian Product
print("\nCartesian Product Relation R:")

R = []

for a in A:
    row = []
    for b in B:
        row.append(min(a, b))
    R.append(row)

R = np.array(R)

print(R)

# Define another fuzzy relation S
S = np.array([
    [0.3, 0.5, 0.6],
    [0.7, 0.2, 0.8],
    [0.5, 0.9, 0.4],
    [0.6, 0.1, 0.7]
])

print("\nFuzzy Relation S:")
print(S)

# Max-Min Composition
print("\nMax-Min Composition of R and S:")

composition = np.zeros((len(R), len(S[0])))

for i in range(len(R)):
    for j in range(len(S[0])):
        values = []

        for k in range(len(S)):
            values.append(min(R[i][k], S[k][j]))

        composition[i][j] = max(values)

print(composition)

Fuzzy Set A = [0.2, 0.5, 0.7, 0.9]
Fuzzy Set B = [0.3, 0.6, 0.4, 0.8]

Union of A and B = [0.3, 0.6, 0.7, 0.9]
Intersection of A and B = [0.2, 0.5, 0.4, 0.8]
Complement of A = [0.8, 0.5, 0.30000000000000004, 0.09999999999999998]
Difference A-B = [0.2, 0.4, 0.6, 0.19999999999999996]

Cartesian Product Relation R:
[[0.2 0.2 0.2 0.2]
 [0.3 0.5 0.4 0.5]
 [0.3 0.6 0.4 0.7]
 [0.3 0.6 0.4 0.8]]

Fuzzy Relation S:
[[0.3 0.5 0.6]
 [0.7 0.2 0.8]
 [0.5 0.9 0.4]
 [0.6 0.1 0.7]]

Max-Min Composition of R and S:
[[0.2 0.2 0.2]
 [0.5 0.4 0.5]
 [0.6 0.4 0.7]
 [0.6 0.4 0.7]]
